version: 2
before:
  hooks:
  - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: aws-login-amd64
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./cmd/aws-login
    binary: aws-login
  - env:
      - CGO_ENABLED=0
    id: aws-login-arm64
    goos:
      - darwin
    goarch:
      - arm64
    main: ./cmd/aws-login
    binary: aws-login
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats: [ 'binary' ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
